### ISSUE TITLE
User interact Epic

### ISSUE THREAD

**Issue by andriyor** [andriyor/archivegram-frontend#3]
### Features:
- [x] add user
- [x] remove user
- [x] fetch added users on load
- [x] user search
https://github.com/ping/instagram_private_api/blob/83b5d01efdd7904589f0a9573349643818d5d38a/instagram_private_api/endpoints/users.py#L72
- [x] show stories (load from db)
    - [x] split stories by day
    - [x] show stories per user
    - [ ] support seen?
- [ ] scheduling
- [ ] scheduling settings
  loading from xz too slow ~ 3 s from one file??
- [ ] cloud support

### Quality:

- [ ] front: split to components
- [ ] beck: better structure
- [ ] beck: separate inst user data  from the story
